import {createHash,randomUUID} from 'node:crypto';
import {mkdirSync,openSync,writeFileSync,closeSync,chmodSync,renameSync,readFileSync,existsSync,lstatSync,realpathSync} from 'node:fs';
import {dirname,join,resolve} from 'node:path';
const MANAGED='<!-- TaskWatch managed goal document v1 -->';
const collections=new Set(['requirements','successCriteria','acceptance','constraints','nonGoals','priorities']);
const layers=new Set(['project','phase','task']);
const string=(value,name,max=4000)=>{if(typeof value!=='string'||!value.trim()||Buffer.byteLength(value)>max)throw new TypeError(`Invalid ${name}`);return value.trim();};
const canonical=value=>{const path=resolve(string(value,'project',4096));return existsSync(path)?realpathSync(path):path;};
const taskItemId=(collection,value)=>`task:item:${createHash('sha256').update(`${collection}\0${value}`).digest('hex').slice(0,20)}`;
function exactSource(userText,source){source=string(source,'operation source',1024);if(!userText.includes(source))throw new Error('Operation source must be an exact quote from the current sidebar message');return source;}
function emptyProject(path){return {path,version:0,summary:null,summarySource:null,items:[],updated:null};}
function sourceLines(source,prefix='来源：'){if(!source)return [`${prefix}尚无`];if(Array.isArray(source.sources)&&source.sources.length)return source.sources.map(ref=>`${prefix}${ref.taskId} · ${ref.messageId} · ${JSON.stringify(ref.quote)}`);return [`${prefix}${source.quote}`];}
function itemLines(items){return items.length?items.flatMap(item=>[`- [${item.collection}] ${item.text}`,...(item.source?item.source.sources?sourceLines(item.source,'  - 来源：'):[`  - 来源：${JSON.stringify(item.source.quote)}`]:[])]).join('\n'):'- 暂无';}
function phaseView(row){if(!row)return {id:null,version:0,name:null,outcome:null,outcomeSource:null,items:[],status:'unset',created:null,ended:null};const body=JSON.parse(row.body);return {id:row.id,version:row.version,name:row.name,outcome:row.outcome,outcomeSource:body.outcomeSource??(row.source?JSON.parse(row.source):null),items:body.items??[],status:row.status,created:row.created,ended:row.ended};}
export class GoalHierarchy{
 constructor(ledger,{dbPath}){if(!ledger?.db||typeof dbPath!=='string')throw new TypeError('GoalHierarchy requires ledger dbPath');this.ledger=ledger;this.db=ledger.db;this.base=join(dirname(dbPath),'projects');this.db.exec(`CREATE TABLE IF NOT EXISTS goal_projects(path TEXT PRIMARY KEY,version INTEGER NOT NULL,body TEXT NOT NULL,updated TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS goal_phases(id TEXT PRIMARY KEY,project TEXT NOT NULL,version INTEGER NOT NULL,name TEXT NOT NULL,outcome TEXT NOT NULL,body TEXT NOT NULL,status TEXT NOT NULL,source TEXT NOT NULL,created TEXT NOT NULL,ended TEXT);
 CREATE TABLE IF NOT EXISTS goal_active_phase(project TEXT PRIMARY KEY,phase_id TEXT NOT NULL REFERENCES goal_phases(id));
 CREATE TABLE IF NOT EXISTS goal_drafts(id TEXT PRIMARY KEY,project TEXT NOT NULL,task TEXT NOT NULL,base_project_version INTEGER NOT NULL,base_phase_version INTEGER NOT NULL,base_main_version INTEGER NOT NULL,base_side_version INTEGER NOT NULL,base_through_seq INTEGER,operations TEXT NOT NULL,source_text TEXT NOT NULL,user_message_id TEXT NOT NULL,user_message_seq INTEGER NOT NULL,check_id TEXT NOT NULL,status TEXT NOT NULL,created TEXT NOT NULL,resolved TEXT,confirmed_by TEXT);
 CREATE TABLE IF NOT EXISTS goal_draft_cards(draft_id TEXT PRIMARY KEY REFERENCES goal_drafts(id),card_id TEXT NOT NULL,task TEXT NOT NULL,main_version INTEGER NOT NULL,through_seq INTEGER,side_version INTEGER NOT NULL,answer TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS goal_revisions(id TEXT PRIMARY KEY,project TEXT NOT NULL,layer TEXT NOT NULL,version INTEGER NOT NULL,body TEXT NOT NULL,source TEXT NOT NULL,task TEXT NOT NULL,created TEXT NOT NULL);`);const draftColumns=this.db.prepare('PRAGMA table_info(goal_drafts)').all().map(column=>column.name);if(!draftColumns.includes('base_through_seq'))this.db.exec('ALTER TABLE goal_drafts ADD COLUMN base_through_seq INTEGER');if(!draftColumns.includes('source_refs'))this.db.exec('ALTER TABLE goal_drafts ADD COLUMN source_refs TEXT');if(!draftColumns.includes('operation_sources'))this.db.exec('ALTER TABLE goal_drafts ADD COLUMN operation_sources TEXT');const revisionColumns=this.db.prepare('PRAGMA table_info(goal_revisions)').all().map(column=>column.name);if(!revisionColumns.includes('source_refs'))this.db.exec('ALTER TABLE goal_revisions ADD COLUMN source_refs TEXT');}
 snapshot(project,task=null){project=canonical(project);const row=this.db.prepare('SELECT * FROM goal_projects WHERE path=?').get(project);const projectView=row?{path:project,version:row.version,...JSON.parse(row.body),updated:row.updated}:emptyProject(project);const active=this.db.prepare('SELECT p.* FROM goal_active_phase a JOIN goal_phases p ON p.id=a.phase_id WHERE a.project=?').get(project);const pending=task?this.pending(project,task):null;return {project:projectView,phase:phaseView(active),phaseHistory:this.db.prepare('SELECT * FROM goal_phases WHERE project=? ORDER BY created,rowid').all(project).map(phaseView),pending};}
 history(project){project=canonical(project);return this.db.prepare('SELECT id,layer,version,source,source_refs,task,created FROM goal_revisions WHERE project=? ORDER BY created,rowid').all(project).map(row=>({id:row.id,layer:row.layer,version:row.version,source:row.source,sourceRefs:row.source_refs?JSON.parse(row.source_refs):null,task:row.task,created:row.created}));}
 pending(project,task){project=canonical(project);const row=this.db.prepare("SELECT * FROM goal_drafts WHERE project=? AND task=? AND status='pending' ORDER BY rowid DESC LIMIT 1").get(project,task);return row?this.#draft(row):null;}
 currentPending(project,task,{mainVersion,sideVersion,throughSeq}){const draft=this.pending(project,task);if(!draft)return null;const view=this.snapshot(project);if(view.project.version===draft.baseProjectVersion&&view.phase.version===draft.basePhaseVersion&&mainVersion===draft.baseMainVersion&&sideVersion===draft.baseSideVersion&&throughSeq===draft.baseThroughSeq)return draft;this.db.prepare("UPDATE goal_drafts SET status='stale',resolved=? WHERE id=? AND status='pending'").run(new Date().toISOString(),draft.id);return null;}
 linkCard(draftId,{cardId,task,revision,answer}){if(!revision||!Number.isSafeInteger(revision.mainVersion)||!Number.isSafeInteger(revision.sideVersion)||(revision.throughSeq!==null&&!Number.isSafeInteger(revision.throughSeq)))throw new Error('Invalid goal draft card revision');this.db.prepare('INSERT INTO goal_draft_cards VALUES (?,?,?,?,?,?,?)').run(string(draftId,'draft id',512),string(cardId,'card id',512),string(task,'task',512),revision.mainVersion,revision.throughSeq,revision.sideVersion,string(answer,'answer'));}
 #draft(row){return {id:row.id,project:row.project,task:row.task,status:row.status,baseProjectVersion:row.base_project_version,basePhaseVersion:row.base_phase_version,baseMainVersion:row.base_main_version,baseSideVersion:row.base_side_version,baseThroughSeq:row.base_through_seq,operations:JSON.parse(row.operations),sourceText:row.source_text,sourceRefs:row.source_refs?JSON.parse(row.source_refs):null,operationSources:row.operation_sources?JSON.parse(row.operation_sources):null,created:row.created,resolved:row.resolved,confirmedBy:row.confirmed_by};}
 taskItems(base){return ['requirements','constraints'].flatMap(collection=>(base?.[collection]??[]).map(text=>({id:taskItemId(collection,text),layer:'task',collection,text})));}
 validate(userText,operations,view){string(userText,'sidebar message');if(!Array.isArray(operations)||!operations.length||operations.length>32)throw new Error('Invalid goal operations');const ids=new Map([...view.project.items,...view.phase.items,...(view.taskItems??[])].map(item=>[item.id,item])),exact=(value,allowed)=>{if(Object.keys(value).some(key=>!allowed.includes(key))||allowed.some(key=>!(key in value)))throw new Error('Invalid goal operation fields');};return operations.map(raw=>{if(!raw||Array.isArray(raw)||typeof raw!=='object')throw new Error('Invalid goal operation');const op=structuredClone(raw);op.tool=string(op.tool,'operation tool',64);if(op.tool==='publish_project_document')throw new Error('Model cannot publish project documents');if(op.tool==='propose_phase_transition'){exact(op,['tool','name','outcome','acceptance','source']);op.name=string(op.name,'phase name',256);op.outcome=string(op.outcome,'phase outcome',2000);op.source=exactSource(userText,op.source);if(!Array.isArray(op.acceptance)||op.acceptance.length>32)throw new Error('Invalid phase acceptance');op.acceptance=op.acceptance.map(value=>string(value,'phase acceptance',1024));return op;}
  if(!layers.has(op.layer))throw new Error('Invalid goal layer');op.source=exactSource(userText,op.source);if(op.layer==='phase'&&!view.phase.id)throw new Error('No active phase; propose a phase transition');if(op.tool==='set_summary'){exact(op,['tool','layer','text','source']);op.text=string(op.text,'summary',4000);return op;}if(op.tool==='add_item'){exact(op,['tool','layer','collection','text','source']);if(!collections.has(op.collection)||(op.layer==='task'&&!['requirements','constraints'].includes(op.collection)))throw new Error('Invalid goal collection');op.text=string(op.text,'item',2000);return op;}if(op.tool==='update_item'||op.tool==='remove_item'){exact(op,op.tool==='update_item'?['tool','layer','itemId','text','source']:['tool','layer','itemId','source']);op.itemId=string(op.itemId,'item id',512);const prior=ids.get(op.itemId);if(!prior||prior.layer!==op.layer)throw new Error('Unknown goal item');if(op.tool==='update_item')op.text=string(op.text,'item',2000);else if(!/(删除|移除|取消|撤销|不再|remove|delete|revoke|drop)/iu.test(op.source))throw new Error('Removal source must explicitly state revocation');return op;}throw new Error('Invalid goal operation tool');});}
 propose({project,task,userText,operations,mainVersion,sideVersion,throughSeq,expectedProjectVersion,expectedPhaseVersion,userMessageId,userMessageSeq,checkId,taskUnderstanding,sourceRefs=null,operationSourceRefs=null,supersedePending=true}){project=canonical(project);this.ledger.snapshot(task);const view=this.snapshot(project,task);if(view.project.version!==expectedProjectVersion||view.phase.version!==expectedPhaseVersion)return {status:'stale'};view.taskItems=this.taskItems(taskUnderstanding);operations=this.validate(userText,operations,view);if(operationSourceRefs&&(!Array.isArray(operationSourceRefs)||operationSourceRefs.length!==operations.length||operationSourceRefs.some(refs=>!Array.isArray(refs)||!refs.length)))throw new Error('Invalid operation sources');const shared=operations.some(op=>op.layer==='project'||op.layer==='phase'||op.tool==='propose_phase_transition');if(!shared)return {status:'task-only',operations};if(throughSeq!==null&&(!Number.isSafeInteger(throughSeq)||throughSeq<0))throw new Error('Invalid execution version');if(supersedePending)this.db.prepare("UPDATE goal_drafts SET status='superseded',resolved=? WHERE project=? AND task=? AND status='pending'").run(new Date().toISOString(),project,task);const id=randomUUID(),now=new Date().toISOString();this.db.prepare('INSERT INTO goal_drafts(id,project,task,base_project_version,base_phase_version,base_main_version,base_side_version,base_through_seq,operations,source_text,user_message_id,user_message_seq,check_id,status,created,resolved,confirmed_by,source_refs,operation_sources) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(id,project,task,view.project.version,view.phase.version,mainVersion,sideVersion,throughSeq,JSON.stringify(operations),userText,userMessageId,userMessageSeq,checkId,'pending',now,null,null,sourceRefs?JSON.stringify(sourceRefs):null,operationSourceRefs?JSON.stringify(operationSourceRefs):null);return this.#draft(this.db.prepare('SELECT * FROM goal_drafts WHERE id=?').get(id));}
 preview(project,draft,{taskUnderstanding}={}){project=canonical(project);const view=this.snapshot(project),taskItems=this.taskItems(taskUnderstanding),items=new Map([...view.project.items,...view.phase.items,...taskItems].map(item=>[item.id,item]));return draft.operations.map(op=>{if(op.tool==='propose_phase_transition')return {tool:op.tool,layer:'phase',before:view.phase.id?{name:view.phase.name,outcome:view.phase.outcome}:null,after:{name:op.name,outcome:op.outcome,acceptance:op.acceptance},source:op.source};if(op.tool==='set_summary')return {tool:op.tool,layer:op.layer,before:op.layer==='project'?view.project.summary:op.layer==='phase'?view.phase.outcome:taskUnderstanding?.goal??null,after:op.text,source:op.source};if(op.tool==='add_item')return {tool:op.tool,layer:op.layer,collection:op.collection,before:null,after:op.text,source:op.source};const prior=items.get(op.itemId);return {tool:op.tool,layer:op.layer,collection:prior?.collection??null,itemId:op.itemId,before:prior?.text??null,after:op.tool==='update_item'?op.text:null,source:op.source};});}
 applyTask(base,operations){let result={goal:base?.goal??'等待明确当前任务',requirements:[...(base?.requirements??[])],constraints:[...(base?.constraints??[])]};for(const op of operations){if(op.layer!=='task')continue;if(op.tool==='set_summary')result.goal=op.text;else if(op.tool==='add_item'){if(!['requirements','constraints'].includes(op.collection))throw new Error('Invalid task collection');if(!result[op.collection].includes(op.text))result[op.collection].push(op.text);}else if(op.tool==='update_item'||op.tool==='remove_item'){const item=this.taskItems(result).find(value=>value.id===op.itemId);if(!item)throw new Error('Unknown task item');const index=result[item.collection].indexOf(item.text);if(op.tool==='update_item')result[item.collection][index]=op.text;else result[item.collection].splice(index,1);}else throw new Error('Invalid task operation');}return result;}
 confirm(project,id,{task,mainVersion,sideVersion,throughSeq,confirmedBy,applyTask,finishCard}={}){project=canonical(project);return this.ledger.transaction(()=>{const row=this.db.prepare('SELECT * FROM goal_drafts WHERE id=? AND project=? AND task=?').get(id,project,task);if(!row||row.status!=='pending')return {status:'stale'};const draft=this.#draft(row),view=this.snapshot(project,task);if(view.project.version!==draft.baseProjectVersion||view.phase.version!==draft.basePhaseVersion||this.ledger.snapshot(task).version!==draft.baseMainVersion||mainVersion!==draft.baseMainVersion||sideVersion!==draft.baseSideVersion||throughSeq!==draft.baseThroughSeq){this.db.prepare("UPDATE goal_drafts SET status='stale',resolved=? WHERE id=?").run(new Date().toISOString(),id);return {status:'stale'};}const operations=JSON.parse(row.operations),now=new Date().toISOString();let projectBody={summary:view.project.summary,summarySource:view.project.summarySource??null,items:view.project.items};let phase={...view.phase,items:[...view.phase.items]};let projectTouched=false,phaseTouched=false,taskOps=[];
  const operationRefs=row.operation_sources?JSON.parse(row.operation_sources):null,allRefs=row.source_refs?JSON.parse(row.source_refs):null;
  const sourceFor=(op,index)=>({quote:op.source,task,userMessageId:row.user_message_id,...(operationRefs?.[index]||allRefs?{sources:operationRefs?.[index]??allRefs}:{})});
  const updateLayer=(target,op,index)=>{const source=sourceFor(op,index);if(op.tool==='set_summary'){if(op.layer==='project'){target.summary=op.text;target.summarySource=source;}else{target.outcome=op.text;target.outcomeSource=source;}}else if(op.tool==='add_item'){target.items.push({id:randomUUID(),layer:op.layer,collection:op.collection,text:op.text,source});}else {const index=target.items.findIndex(item=>item.id===op.itemId);if(index<0)throw new Error('Goal item changed');if(op.tool==='update_item')target.items[index]={...target.items[index],text:op.text,source};else target.items.splice(index,1);}};
  for(const [index,op] of operations.entries()){if(op.layer==='task'){taskOps.push(op);continue;}if(op.tool==='propose_phase_transition'){if(phase.id)this.db.prepare("UPDATE goal_phases SET status='archived',ended=? WHERE id=?").run(now,phase.id);const phaseId=randomUUID(),version=view.phase.version+1,phaseSource=sourceFor(op,index),body={outcomeSource:phaseSource,items:op.acceptance.map(text=>({id:randomUUID(),layer:'phase',collection:'acceptance',text,source:phaseSource}))};this.db.prepare('INSERT INTO goal_phases VALUES (?,?,?,?,?,?,?,?,?,NULL)').run(phaseId,project,version,op.name,op.outcome,JSON.stringify(body),'active',JSON.stringify(phaseSource),now);this.db.prepare('INSERT INTO goal_active_phase VALUES (?,?) ON CONFLICT(project) DO UPDATE SET phase_id=excluded.phase_id').run(project,phaseId);phase={id:phaseId,version,name:op.name,outcome:op.outcome,outcomeSource:phaseSource,items:body.items,status:'active',created:now,ended:null};phaseTouched=true;continue;}if(op.layer==='project'){updateLayer(projectBody,op,index);projectTouched=true;}else {if(!phase.id)throw new Error('No active phase');updateLayer(phase,op,index);phaseTouched=true;}}
  if(phaseTouched&&phase.id&&phase.version===view.phase.version)phase.version=view.phase.version+1;let projectVersion=view.project.version;if(projectTouched){projectVersion++;this.db.prepare('INSERT INTO goal_projects(path,version,body,updated) VALUES (?,?,?,?) ON CONFLICT(path) DO UPDATE SET version=excluded.version,body=excluded.body,updated=excluded.updated').run(project,projectVersion,JSON.stringify(projectBody),now);this.db.prepare('INSERT INTO goal_revisions(id,project,layer,version,body,source,task,created,source_refs) VALUES (?,?,?,?,?,?,?,?,?)').run(randomUUID(),project,'project',projectVersion,JSON.stringify(projectBody),row.source_text,task,now,row.source_refs);}if(phaseTouched&&phase.id){this.db.prepare('UPDATE goal_phases SET version=?,outcome=?,body=? WHERE id=?').run(phase.version,phase.outcome,JSON.stringify({outcomeSource:phase.outcomeSource,items:phase.items}),phase.id);this.db.prepare('INSERT INTO goal_revisions(id,project,layer,version,body,source,task,created,source_refs) VALUES (?,?,?,?,?,?,?,?,?)').run(randomUUID(),project,'phase',phase.version,JSON.stringify(phase),row.source_text,task,now,row.source_refs);}if(taskOps.length&&typeof applyTask==='function')applyTask(taskOps,row);
  const card=this.db.prepare('SELECT * FROM goal_draft_cards WHERE draft_id=?').get(id);if(card&&typeof finishCard==='function')finishCard({cardId:card.card_id,task:card.task,revision:{mainVersion:card.main_version,throughSeq:card.through_seq,sideVersion:card.side_version},answer:card.answer});this.db.prepare("UPDATE goal_drafts SET status='confirmed',resolved=?,confirmed_by=? WHERE id=?").run(now,string(confirmedBy,'confirmed by',256),id);this.#writePrivate(project);return {status:'confirmed',projectVersion,phaseVersion:phase.version,taskOperations:taskOps,cardId:card?.card_id??null};});}
 dismiss(project,id,task){project=canonical(project);return !!this.db.prepare("UPDATE goal_drafts SET status='dismissed',resolved=? WHERE id=? AND project=? AND task=? AND status='pending'").run(new Date().toISOString(),id,project,task).changes;}
 #hash(project){return createHash('sha256').update(canonical(project)).digest('hex');}
 #markdown(project,{taskGoal=null,published=false}={}){const view=this.snapshot(project);const lines=[MANAGED,published?'# TaskWatch 已发布目标视图':'# TaskWatch 私有目标主档','',published?'> TaskWatch 监督理解，仅供参考，不代表主 Agent 已收到新授权。':'> 此文档由 TaskWatch 根据结构化版本确定性生成。','',`## 项目主旨 · v${view.project.version}`,view.project.summary??'尚未建立项目主旨',...sourceLines(view.project.summarySource),'',itemLines(view.project.items),'',`## 当前阶段 · v${view.phase.version}`,view.phase.name?`**${view.phase.name}**：${view.phase.outcome}`:'尚未建立当前阶段',...sourceLines(view.phase.outcomeSource),'',itemLines(view.phase.items)];if(taskGoal!==null)lines.push('','## 当前任务',taskGoal||'尚未明确');if(view.phaseHistory.length)lines.push('','## 阶段历史',...view.phaseHistory.map(p=>`- ${p.name??'未命名'} · v${p.version} · ${p.status}`));return lines.join('\n')+'\n';}
 #atomic(path,body){mkdirSync(dirname(path),{recursive:true,mode:0o700});if(existsSync(path)&&lstatSync(path).isSymbolicLink())throw new Error('Goal document path must not be a symbolic link');const temp=`${path}.${process.pid}.${randomUUID()}.tmp`;const fd=openSync(temp,'wx',0o600);try{writeFileSync(fd,body,'utf8');}finally{closeSync(fd);}chmodSync(temp,0o600);renameSync(temp,path);chmodSync(path,0o600);}
 #writePrivate(project){const path=join(this.base,this.#hash(project),'intent.md');this.#atomic(path,this.#markdown(project));return path;}
 document(project){project=canonical(project);const path=join(this.base,this.#hash(project),'intent.md');if(!existsSync(path))this.#writePrivate(project);return {privatePath:path,project,version:this.snapshot(project).project.version};}
 publish(project,workspace,{taskGoal=null}={}){project=canonical(project);workspace=canonical(workspace);if(project!==workspace)throw new Error('Publish workspace does not match project');const parent=join(workspace,'.taskwatch');if(existsSync(parent)&&(!lstatSync(parent).isDirectory()||lstatSync(parent).isSymbolicLink()))throw new Error('TaskWatch publish directory must be a real directory');const path=join(parent,'intent.md');if(existsSync(path)&&(lstatSync(path).isSymbolicLink()||!lstatSync(path).isFile()||!readFileSync(path,'utf8').startsWith(MANAGED)))throw new Error('Existing goal document is not managed by TaskWatch');this.#atomic(path,this.#markdown(project,{taskGoal,published:true}));return {status:'published',path,projectVersion:this.snapshot(project).project.version};}
}
